name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main # Triggers on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the runner environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '18.19.0' # Updated to a compatible Node.js version (e.g., 18.19.0, 18.x, or 20.x)
          cache: 'npm' # Optional: Caches npm dependencies to speed up future builds

      - name: Install dependencies
        run: npm ci # 'ci' is generally recommended for CI environments for faster, more reliable installs

      - name: Build
        run: npm run build # This script should execute 'ng build --configuration production' or similar
        env:
          CI: true # Often used by build tools

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive --only hosting # Specify '--only hosting' if you're just deploying hosting
        # Add --project YOUR_FIREBASE_PROJECT_ID if not set in .firebaserc or if you need to override
